name: Label closed issues

on:
  issues:
    types:
      - closed

jobs:
  label-closed-issues:
    runs-on: ubuntu-latest
    steps:
    - name: add label
      uses: andymckay/labeler@22d5392de2b725cea4b284df5824125054049d84
      with:
        add-labels: 'resolution:resolved'
        repo-token: ${{ secrets.LISA_PAT }}
