name: Label opened prs

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  move_prs:
    runs-on: ubuntu-latest

    steps:
    - name: Move to the PR-WIP column
      uses: leonsteinhaeuser/project-beta-automations@v2.0.1
      with:
        gh_token: ${{ secrets.LISA_PAT }}
        organization: lisa-analyzer
        project_id: 3
        resource_node_id: ${{ github.event.issue.node_id }}
        status_value: 'PR WIP'
    - name: Add WIP label
      uses: andymckay/labeler@22d5392de2b725cea4b284df5824125054049d84
      with:
        add-labels: '🏗 resolution:wip'
        repo-token: ${{ secrets.LISA_PAT }}
