name: Import created issues

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  move_issues:
    runs-on: ubuntu-latest

    steps:
    - name: Move to the TODO column
      uses: leonsteinhaeuser/project-beta-automations@v2.0.1
      with:
        gh_token: ${{ secrets.LISA_PAT }}
        organization: lisa-analyzer
        project_id: 3
        resource_node_id: ${{ github.event.issue.node_id }}
        status_value: Todo
    
