name: 'Move ready PRs'

on:
  pull_request:
    types:
      - unlabeled

jobs:
  move-prs:
    if: github.event.label.name == '🏗 resolution:wip'
    runs-on: ubuntu-latest
    steps:
    - name: Move to the PR-READY column
      uses: leonsteinhaeuser/project-beta-automations@v2.0.1
      with:
        gh_token: ${{ secrets.LISA_PAT }}
        organization: lisa-analyzer
        project_id: 3
        resource_node_id: ${{ github.event.pull_request.node_id }}
        status_value: 'PR Ready'
