name: 'Move ready PRs'

on:
  pull_request:
    types:
      - unlabeled

jobs:
  move-prs:
    if: github.event.label.name == 'resolution:wip'
    runs-on: ubuntu-latest
    steps:
    - name: Move to the PR-READY column
      uses: alex-page/github-project-automation-plus@v0.7.1
      with:
        project: LiSA
        column: PR-READY
        repo-token: ${{ secrets.LISA_PAT }}
