name: Move resolved issues

on:
  issues:
    types:
      - labeled

jobs:
  move-resolved-issues:
    if: github.event.label.name == '🎊 resolution:resolved'
    runs-on: ubuntu-latest
    steps:
    - name: Move to the DONE column
      uses: leonsteinhaeuser/project-beta-automations@v2.0.1
      with:
        gh_token: ${{ secrets.LISA_PAT }}
        organization: lisa-analyzer
        project_id: 3
        resource_node_id: ${{ github.event.issue.node_id }}
        status_value: Done
